### ISSUE TITLE
Error of 'bazel build -c opt //neuron/java:tensorflow-lite-neuron'

### ISSUE THREAD

**Issue by sheirving** [MediaTek-NeuroPilot/tflite-neuron-delegate#10]
System Config:
- bazel version: 5.2.0
- system: mac os
- ndk: 19.2.5345600

直接运行报错：
![image](https://user-images.githubusercontent.com/12372742/180724770-3ddbd976-124f-42cb-a461-682979bc576d.png)
大概与libneuron_performance.a库不兼容，请问你们使用的环境是什么样的？谢谢

**Comment by freedomtan** [comment]
please try ```bazel build --config android_arm64 -c opt //neuron/java:tensorflow-lite-neuron```

**Comment by sheirving** [comment]
Build completed successfully, thankyou very much!
