### ISSUE TITLE
对MT6771(P60)不适用

### ISSUE THREAD

**Issue by peyer** [MediaTek-NeuroPilot/tflite-neuron-delegate#9]
你好，我有一台MT6771(P60)的设备，设备上没有找到 libneuronusdk_adapter.mtk.so 或者 libneuronusdk_adapter.mtk.so.5；想咨询一下MT6771的apu sdk、demo在哪里可以下载呢？

**Comment by freedomtan** [comment]
Sorry, as far as I know, Only SoCs in [Dimensity series](https://www.mediatek.com/products/smartphones/dimensity-5g) are supported. 

For Helio P60, please try [TFLite's NNAPI delegate](https://www.tensorflow.org/lite/android/delegates/nnapi).
